added courses-crud, created routes for courses
vladysllav/LearnIT pull request #12
Opened 2023-10-15 01:31 UTC by danraponga

*created courses schemas

*created courses-crud

*created courses routes that are included in api/routers

*removed items related code 

*fixed a bug in relationships between course and user tables

2023-10-18 09:17 UTC, vladysllav requested changes

2023-10-18 09:17 UTC, vladysllav commented on app/api/courses/routes.py
> +@router.post('/create')
Endpoint should be "courses/" POST

2023-10-18 09:17 UTC, vladysllav commented on app/api/courses/routes.py
> +@router.post('/update/{course_id}')
Endpoint should be "courses/{id}" PUT or PATCH

2023-10-18 09:17 UTC, vladysllav commented on app/schemas/course.py
> +class CourseRead(BaseCourse):
We should have id field as well

2023-10-20 20:21 UTC, danraponga commented on app/api/courses/routes.py
> +@router.post('/create')
fixed

2023-10-20 20:21 UTC, danraponga commented on app/api/courses/routes.py
> +@router.post('/update/{course_id}')
fixed

2023-10-20 20:21 UTC, danraponga commented on app/schemas/course.py
> +class CourseRead(BaseCourse):
fixed

2023-10-21 02:04 UTC, vladysllav approved these changes

2023-10-24 21:49 UTC, merged