created module model
vladysllav/LearnIT pull request #14
Opened 2023-10-24 22:43 UTC by danraponga

2023-10-27 08:43 UTC, vladysllav requested changes
Не вистачає звʼязку з курсом, додай foreign key до моделі курсу

2023-10-30 04:07 UTC, vladysllav requested changes
Виправ коментар і можеш одразу заливати

2023-10-30 04:07 UTC, vladysllav commented on app/models/course.py
> +    modules = relationship("Module", back_populates="courses")
back_populates повинен бути  course, в тебе ж 1 до багатьох звʼязок, а не M2M

2023-10-30 15:44 UTC, danraponga commented on app/models/course.py
> +    modules = relationship("Module", back_populates="courses")
fixed

2023-10-30 15:45 UTC, merged