Lit 19.create module cruds
vladysllav/LearnIT pull request #15
Opened 2023-10-30 18:11 UTC by danraponga

** created cruds for modules. it gives the  ability to create, read one, read all, update and delete module objects with access check

* created module schemas for cruds

* defined endpoints for modules with `"/courses/{course_id}/modules"` prefix

* created a separate file in the module folder, which responsible for access rights. it's functionality is used at endpoints.

2023-10-31 09:23 UTC, vladysllav requested changes
Сам функціонал ок, але структурно краще по іншому код розбити

2023-10-31 09:23 UTC, vladysllav commented on app/api/modules/check_access.py
> +            (course.created_by_id == current_user.id and user.is_superuser(current_user)):
А чому ти суперюзеру забороняєш щось робити. Мені здається в тебе умова не корректно відпрацювувати буде, бо зараз якщо користувач це суперюзер ти повернеш помилку

2023-10-31 09:23 UTC, vladysllav commented on app/api/modules/check_access.py
> +def check_course_existence(db: Session, course_id: int):
Краще зроби це як dependency, та просто додавай це у роути, щось типу такого

def get_course(db: Session = Depends(get_db), course_id: int) -> Course:
    course = db.query(Course).filter(Course.id == course_id).first()
    if not course:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Course not found")
    return course
    
    
   І потім у роутах додай course: Course = Depends(get_course)
   Так само з усіма методами зроби і поклади їх у файл окремий у папку dependencies

2023-10-31 09:23 UTC, vladysllav commented on app/api/modules/routes.py
> +    module = crud_module.get(db=db, id=id)
Це потрібно робити в середині крудів, а не тут, передавай просто айді, або як я сказав за допомогою депенденсі

2023-10-31 09:23 UTC, vladysllav commented on app/api/routers.py
> +api_router.include_router(module_routes.router, prefix="/courses/{course_id}/modules",
Роути для модулей повинні бути всередині курсів, тобто нехай буде один роут тут /courses а в середині нього створиш /id/modules і так далі

2023-10-31 09:23 UTC, vladysllav commented on app/schemas/module.py
> +    image: Optional[str] = Field(None, example='some/path/to/image')
Не шлях до імеджу, а url зберігається в базі

2023-11-01 03:46 UTC, danraponga commented on app/schemas/module.py
> +    image: Optional[str] = Field(None, example='some/path/to/image')
fixed

2023-11-01 03:46 UTC, danraponga commented on app/api/routers.py
> +api_router.include_router(module_routes.router, prefix="/courses/{course_id}/modules",
fixed

2023-11-01 03:46 UTC, danraponga commented on app/api/modules/routes.py
> +    module = crud_module.get(db=db, id=id)
fixed

2023-11-01 03:46 UTC, danraponga commented on app/api/modules/check_access.py
> +def check_course_existence(db: Session, course_id: int):
fixed

2023-11-01 03:46 UTC, danraponga commented on app/api/modules/check_access.py
> +            (course.created_by_id == current_user.id and user.is_superuser(current_user)):
fixed

2023-11-01 03:54 UTC, danraponga commented
** module code structure was changed

* created dependencies for check access and get course/module

* now module endpoints is a part of course endpoints, not a separate router.

* minor changes in module and course cruds

* changed example at the module schema for image field

2023-11-02 04:30 UTC, vladysllav approved these changes

2023-11-02 18:12 UTC, merged