created a Invitation model with a FK to the User table  by  user.id
vladysllav/LearnIT pull request #17
Opened 2023-11-05 02:46 UTC by danraponga

** created a Invitation model with a FK to the User table  by  user.id.

* status changed to be more flexible, suitable for different models

2023-11-05 03:38 UTC, vladysllav requested changes

2023-11-05 03:38 UTC, vladysllav commented on app/models/user.py
> +    expired = 'expired'      #Invitation flow, if token has expired
Цей статус нам не потрібен, якщо заекспайрився інвітейшн це ж не означає що юзер заекспайрився

2023-11-05 03:38 UTC, vladysllav commented on app/models/user.py
> +    expired = 'expired'      #Invitation flow, if token has expired
Такс, по перше назви це InvitationStatus, а не UserStatus бо як ти баиш вводиш в оману, бо я думав що це статус юзера

По друге нам все одно статус expired не потрібен, у нас у токені зашите це поле тому статуси повинні бути лише active, accepted, canceled, іншиз не потрібно, бо наприклад як ми будемо сетати expired якщо в нас це лише у токені, який в нас ніде не зберігається, відповідно цей статус буде юзлес

2023-11-05 18:35 UTC, danraponga commented on app/models/user.py
> +    expired = 'expired'      #Invitation flow, if token has expired
fixed

2023-11-06 08:23 UTC, vladysllav requested changes

2023-11-06 08:23 UTC, vladysllav commented on app/api/users/routes.py
> +from typing import Annotated, Any, List
Навіщо тобі цей імпорт?

2023-11-06 08:23 UTC, vladysllav commented on app/api/users/routes.py
> +from fastapi import APIRouter, Body, Depends, HTTPException, Response, Depends
НАвіщо дублювати Depends?

2023-11-06 08:23 UTC, vladysllav commented on app/core/security.py
> +    secret_key = settings.SECRET_KEY
Можна не створювати для цього окремі змінні, просто передавай одразу до функції

2023-11-06 15:45 UTC, danraponga commented on app/core/security.py
> +    secret_key = settings.SECRET_KEY
fixed

2023-11-06 15:45 UTC, danraponga commented on app/api/users/routes.py
> +from fastapi import APIRouter, Body, Depends, HTTPException, Response, Depends
fixed

2023-11-06 15:45 UTC, danraponga commented on app/api/users/routes.py
> +from typing import Annotated, Any, List
fixed

2023-11-06 15:46 UTC, merged