update invitation flow, created invitatiom migration
vladysllav/LearnIT pull request #18
Opened 2023-11-07 01:51 UTC by danraponga

updated invitation flow. created a migration. routes were written, services were expanded

2023-11-08 22:05 UTC, danraponga commented
** updated the invitation flow.
* created an activation user endpoint
* now we can send emails, for this jinja2 library have been added to the pyproject.toml. Make: docker-compose build, to accept this changes.
* user invitation flow written within the single Service of the same name. 
* we are tracking exceptions in the endpoints.
* minor changes in the other files.

2023-11-10 01:35 UTC, vladysllav requested changes
З 3 міграцій файлів зроби одну: навіщо нам три якщо можна створити одну, ти ж коміт до дев не вливав ще, відповідно твої міграції тільки ти бачив, щоб не засоряти історію міграцій введи правило - 1 пул реквес - 1 міграція максимум

2023-11-10 01:35 UTC, vladysllav commented on app/api/users/routes.py
> +    user = invitation_service.user_repo.get_by_email(email=user_schema.email)
Ні ні ні, це не по оніон архітектурі, ти не повинен викликати методи репозиторію через сервіс, у ендпоінтах ти ВИКЛЮЧНО працюєш з віхдними даними та визідними, без ніякох логіки, логіку ти вже у сервісі пиши, тобто всі перевірки та будь яка робота з репозиторіємо повинна будти у сервісі

2023-11-10 01:35 UTC, vladysllav commented on app/api/users/routes.py
> +    user = invitation_service.user_repo.get_by_id(id=payload['sub'])
Так само і тут, роути - це найвищий рівень у архітектурі луковій, тут не повинно бути ніяких перевірок зайвих. Той самий декод токен, ти можеш це як депенденсі зробити, і перевіряти це у ньому, хоча дивна чесно кажучи перевірка на expired. Але її краще у депенденсі перенести щоб роут мав лише депенденсі і виклик методу сервіса і все

2023-11-10 01:35 UTC, vladysllav commented on app/repositories/user_repository.py
> +    def authenticate(self, email: str, password: str) -> User:
Цей метод не відповідає за роботу з даними, а більше за бізнес логіку, тому він повинен бути не у репозиторії, а у сервісі

2023-11-10 01:35 UTC, vladysllav commented on app/services/user_service.py
> +class UserInvitationService:
В тебе повинно бути два окремі сервіси UserService де буде все повʼязано з юзером та InvitationService де буде все повʼязано з invitation

2023-11-10 02:08 UTC, danraponga commented on app/api/users/routes.py
> +    user = invitation_service.user_repo.get_by_id(id=payload['sub'])
перевірка норм, бо в самому методі decode_token у нас вертається None якщо токен заекспайрений

2023-11-10 23:00 UTC, danraponga commented on app/services/user_service.py
> +class UserInvitationService:
fixed

2023-11-10 23:00 UTC, danraponga commented on app/repositories/user_repository.py
> +    def authenticate(self, email: str, password: str) -> User:
fixed

2023-11-10 23:00 UTC, danraponga commented on app/api/users/routes.py
> +    user = invitation_service.user_repo.get_by_id(id=payload['sub'])
fixed

2023-11-10 23:00 UTC, danraponga commented on app/api/users/routes.py
> +    user = invitation_service.user_repo.get_by_email(email=user_schema.email)
fixed

2023-11-11 07:15 UTC, vladysllav approved these changes
Онови лок файл і заливай

2023-11-11 07:15 UTC, vladysllav commented on pyproject.toml
> +Jinja2 = "^3.1.2"
Не забудь lock файл оновити

2023-11-20 15:13 UTC, merged