add crud_lessons
vladysllav/LearnIT pull request #19
Opened 2023-12-02 13:47 UTC by OleksandrBrusyltsev

2023-12-03 12:57 UTC, danraponga commented on app/schemas/lessons.py
> +    module_id:Optional[int] = Field(None, example='1')
трішки ім'я переплутав. тут напевно має бути BaseLesson. і по ідеї нам не потрібен module_id в базовому классі, хіба що в LessonRead. а при створенні lesson, module_id має встановлюватись автоматично

2023-12-03 12:57 UTC, danraponga commented on app/dependencies/lessons.py
> +    return lessons
думаю краще отримувати об'єкт по айді в crud`ах, тим більше в нас є базовий метод get.

2023-12-03 12:57 UTC, danraponga commented on app/crud/crud_lessons.py
> +        lesson_data['created_at'] = datetime.utcnow()
думаю тут можна приймати module_id як аргумент в фукнцію і додавати його в lesson_data щоб в нас при створенні уроку автоматично "встановлювався" зв'язок.
щось типу: lesson_data[module_id] = module_id.

2023-12-03 12:57 UTC, danraponga commented on app/api/routers.py
> +api_router.include_router(lessons_routes.router, prefix="/lessons", tags=["lessons"])
lessons це частина модулів, а модулі - частина курсів. тому нам потрібно lesson ендпоінти прописувати в courses/routes.py, там якраз знайдеш референс на прикладі modules ендпоінтів)

2023-12-03 17:30 UTC, OleksandrBrusyltsev commented on app/api/routers.py
> +api_router.include_router(lessons_routes.router, prefix="/lessons", tags=["lessons"])
спасибо)исправлю все

2023-12-04 04:40 UTC, vladysllav requested changes

2023-12-04 04:40 UTC, vladysllav commented on app/dependencies/lessons.py
> +    return lessons
Я думаю можемо залишити в депенденсі, більш ніж ок зараз

2023-12-04 04:40 UTC, vladysllav commented on app/api/lessons/routes.py
> +@router.put('/{lessons_id}')
Я хочу бачити ще patch метод для partial update

2023-12-04 04:40 UTC, vladysllav commented on app/crud/crud_lessons.py
> +        lesson_data['created_at'] = datetime.utcnow()
Так, це обовʼязково, ми курс та модуль з url отримуємо, і повинні одразу встановити звʼязок інакше в нас уроки загубляться

2023-12-04 21:36 UTC, danraponga commented on app/schemas/lessons.py
>      module_id:Optional[int] = Field(None, example='1')
краще прибрати module_id з базового классу, тому що ти унаслідковуєшся від BaseLessons в LessonsCreate і LessonUpdate, а при створенні чи оновленні обєкта ніхто не повинен мати доступ до айді, він має генеруватись автоматично базою сервером/бд.

2023-12-04 21:36 UTC, danraponga commented on app/api/courses/routes.py
> +@router.post("/{module_id}/lessons/{lessons_id}")
неправильна структура урлів: додай course_id і modules до url, бо в нас кожен модуль прив'язаний до конкретного курса, а перед module_id у нас /modules має бути.
приклад: `/{course_id}/modules/{module_id}/lessons/{lesson_id}`
у нас даний роутер має префікс `course`, весь інший шлях ми маємо прописувати в урлах ендпоінтів.
виправ це в усіх ендпоінтах і буде супер 👍🏻

2023-12-05 02:12 UTC, vladysllav requested changes

2023-12-05 02:12 UTC, vladysllav commented on app/api/courses/routes.py
> +                   module: Module = Depends(get_module),
В тебе або module повинен тут бути або module_id, ти ж в депенденсі отримуєш як раз модуль за module_id, тому навіщо дублювати цей параметр, вистачить просто депенденсі з модулем

І тут ще не правильний юрл, courses/...тут очікую айді курсу, а в тебе айді модуля, якщо читати юрл, то буде місандерстенд. Краще додай ще частину /course_id/modules як Діма запропонував, а сам курс просто перевіряй айді що він існує

2023-12-05 02:12 UTC, vladysllav commented on app/api/courses/routes.py
> +@router.get('/{module_id}/lessons/{lessons_id}')
По іншим ендпоінтам так само

2023-12-06 09:35 UTC, merged