now we can upload files to the s3 storage
vladysllav/LearnIT pull request #25
Opened 2023-12-09 23:11 UTC by danraponga

* created s3service that creates a connection to the bucket and uploads files to it.
* created endpoint that upload files to the s3bucket
* updated pyproject.toml: added boto3 library

**created init file in the `api/courses/`for imports, package definition

2023-12-11 07:29 UTC, vladysllav requested changes

2023-12-11 07:29 UTC, vladysllav commented on app/api/s3.py
> +    return url_to_file
Краще повертати не просто юрл, а json обʼєкт з урлом всередині

2023-12-11 07:29 UTC, vladysllav commented on app/services/s3.py
> +        print(client)
Прінтів у коді не повинно бути, не забувай прибирате їх

2023-12-11 07:29 UTC, vladysllav commented on app/services/s3.py
> +        bucket = os.getenv('S3_BUCKET')
Це краще в init прописати, і через self.bucket звертатись

2023-12-11 07:29 UTC, vladysllav commented on app/services/s3.py
> +            url = f"https://{bucket}.s3.{region}.amazonaws.com/{urlencode(file.filename.encode('utf8'))}"
Це аткож краще в ініті формувати, якось сильно хардкорно юрл виглядає, краще його або в ініті, а краще взагалі бакет та регіон у конфігах в сетінгах мати і там же формувати юрл

2023-12-11 07:29 UTC, vladysllav commented on app/services/s3.py
> +            print(f'{file.filename} uploaded successfully')
Видали

2023-12-13 23:50 UTC, danraponga commented on app/api/s3.py
> +    return url_to_file
fixed

2023-12-13 23:50 UTC, danraponga commented on app/services/s3.py
> +        print(client)
fixed

2023-12-13 23:50 UTC, danraponga commented on app/services/s3.py
> +        bucket = os.getenv('S3_BUCKET')
fixed

2023-12-13 23:50 UTC, danraponga commented on app/services/s3.py
> +            url = f"https://{bucket}.s3.{region}.amazonaws.com/{urlencode(file.filename.encode('utf8'))}"
fixed

2023-12-13 23:50 UTC, danraponga commented on app/services/s3.py
> +            print(f'{file.filename} uploaded successfully')
fixed

2023-12-14 04:21 UTC, vladysllav requested changes

2023-12-14 04:21 UTC, vladysllav commented on app/core/config.py
> +    S3_URL_TEMPLATE = "https://{bucket}.s3.{region}.amazonaws.com/{filename}"
Зроби змінну S3_BASE_URL = "https://{S3_BUCKET}.s3.{AWS_REGION}.amazonaws.com" і звичайною конкатенацією просто додавай вже файлнейм у контроллерах

2023-12-16 00:57 UTC, merged