Course rating
vladysllav/LearnIT pull request #31
Opened 2024-02-27 07:34 UTC by Danemm99

Adding rating to course

2024-02-27 10:09 UTC, vladysllav requested changes

2024-02-27 10:09 UTC, vladysllav commented on .gitignore
> +lms_project/
Що це за папка і навіщо вона тут

2024-02-27 10:09 UTC, vladysllav commented on app/models/course.py
> +Column('user_id', Integer, ForeignKey('user.id')),
Навіщо прибрав таб?

2024-02-27 10:09 UTC, vladysllav commented on app/models/course.py
> +    rating_value = Column(Float, nullable=False)
Чому флоат, ми можемо поставити 4.5 бали? Я думаю тут краще число використовувати

2024-02-27 10:09 UTC, vladysllav commented on app/models/user.py
> +    ratings = relationship("CourseRating", back_populates="user")
Я думаю нам це поле не потрібно, не думаю що в нас виникне ситуація коли ми захочемо витягнути всі оцінки користувача, але нехай вже буде

2024-02-27 10:09 UTC, vladysllav commented on app/api/courses/routes.py
> +        average_rating = sum(rating.rating_value for rating in ratings) / len(ratings)
Це можна зробити як hybrid property чи просто property у моделі курс, щоб постійно не рахувати

2024-02-27 10:09 UTC, vladysllav commented on app/api/courses/routes.py
> +@router.post("/courses/{course_id}/rate", dependencies=[Depends(allow_add_rating)])
url по ресту будуються інакше, якщо ти створюєш обʼєкв Rating то ендпоінт повинен бути /courses/course_id/ratings

2024-02-27 10:09 UTC, vladysllav commented on app/api/courses/routes.py
> +def rate_course(
Тут краще буде назвати create_course_rating

2024-02-27 10:09 UTC, vladysllav commented on app/api/courses/routes.py
> +    course: Course = Depends(get_course),
Ти використовуєш лише айді, тобі не потрібно отримувати весь обʼєкт курсу

2024-02-27 10:09 UTC, vladysllav commented on app/api/courses/routes.py
> +    rating_value = rating_data.rating_value
Навіщо окремо брати це значення, якщо можна просто **rating_data зробити

2024-02-27 10:09 UTC, vladysllav commented on app/crud/crud_course.py
> +    def create(
Чим тобі базовий метод в базовому класі не підійшов, він же такий самий

2024-02-27 10:09 UTC, vladysllav commented on app/db/session.py
> +SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine, expire_on_commit=False)
Яка була потреба ц цьому флазі?

2024-02-27 10:09 UTC, vladysllav commented on app/dependencies/users.py
> +class PermissionCheckerRating:
Прибери цей клас

2024-03-07 16:44 UTC, danraponga requested changes

2024-03-07 16:44 UTC, danraponga commented on alembic/versions/2024_03_06_1811-2cdf6c3dd0f1_course_rating_updates.py
> +    # ### end Alembic commands ###
Ця міграція пуста, а минулу ти видалив. В підсумку, нічого в бд не зальється.

2024-03-07 16:44 UTC, danraponga commented on app/api/courses/routes.py
> +    course = crud_course.update_course_rating(db, course_id=course_id)
Цей ендпоінт повинен повертати тільки інфу про конкретний курс. Тут не повинна бути update логіка. 
Да і в самому методі update_course_rating немає необхідності, нижче написав чому.

2024-03-07 16:44 UTC, danraponga commented on app/crud/crud_course.py
> +            raise HTTPException(status_code=400, detail="Invalid rating. Must be between 0 and 5.")
Рейтинг може бути тільки від 1 до 5. Нуль не можна поставити, це не має сенсу.

2024-03-07 16:44 UTC, danraponga commented on app/crud/crud_course.py
> +
Course.average_rating вже повертає середній рейтинг, тому в полі Course.rating немає необхідності, відповідно в цьому методі теж.

2024-03-07 16:44 UTC, danraponga commented on app/models/course.py
> +
Гуд. Але ще можна додати hybrid_property.expression, щоб можна було в sql запитах юзати average_rating. Наприклад, щоб в майбутньому фільтрувати курси по рейтингу тощо.

2024-03-12 04:29 UTC, vladysllav requested changes

2024-03-12 04:29 UTC, vladysllav commented on app/api/users/routes.py
> +from fastapi import APIRouter, Body, Depends, HTTPException
Навіщо нам дублювати цей імпорт, він же вище є, і нижній нафіга, видалі всі unused imports

2024-03-12 04:29 UTC, vladysllav commented on app/crud/crud_course.py
> +        course.rating = course.average_rating
Навіщо ми це робимо, навіщо нам поле rating та average_rating водночас, чому 1 не залишити, те яке автоматично рахується, і назвати його rating

2024-03-12 04:29 UTC, vladysllav commented on app/models/course.py
> +    rating_value = Column(Integer, nullable=False)
Краще назвати value, в нас і так таблиця називається courserating не для чого дублювати слово rating

2024-03-13 17:43 UTC, Danemm99 commented on .gitignore
> +lms_project/
Fixed

2024-03-13 17:43 UTC, Danemm99 commented on app/models/course.py
> +Column('user_id', Integer, ForeignKey('user.id')),
Fixed

2024-03-13 17:43 UTC, Danemm99 commented on app/models/course.py
> +    rating_value = Column(Float, nullable=False)
Fixed

2024-03-13 17:43 UTC, Danemm99 commented on app/models/user.py
> +    ratings = relationship("CourseRating", back_populates="user")
Так і залишив

2024-03-13 17:43 UTC, Danemm99 commented on app/api/courses/routes.py
> +        average_rating = sum(rating.rating_value for rating in ratings) / len(ratings)
Fixed

2024-03-13 17:44 UTC, Danemm99 commented on app/api/courses/routes.py
> +@router.post("/courses/{course_id}/rate", dependencies=[Depends(allow_add_rating)])
Fixed

2024-03-13 17:44 UTC, Danemm99 commented on app/api/courses/routes.py
> +def rate_course(
Fixed

2024-03-13 17:44 UTC, Danemm99 commented on app/api/courses/routes.py
> +    course: Course = Depends(get_course),
Fixed

2024-03-13 17:44 UTC, Danemm99 commented on app/api/courses/routes.py
> +    rating_value = rating_data.rating_value
Fixed

2024-03-13 17:45 UTC, Danemm99 commented on app/crud/crud_course.py
> +    def create(
Вирішили, що так і залишемо

2024-03-13 17:45 UTC, Danemm99 commented on app/db/session.py
> +SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine, expire_on_commit=False)
Fixed

2024-03-13 17:45 UTC, Danemm99 commented on app/dependencies/users.py
> +class PermissionCheckerRating:
Fixed

2024-03-13 22:28 UTC, danraponga requested changes

2024-03-13 22:28 UTC, danraponga commented on app/api/users/routes.py
> +from fastapi import Response
На 2 строчки нижче є імпорт :
`from fastapi import APIRouter, Body, Depends, HTTPException`
Можна там же вписати Response, щоб не дублювати імпорт

2024-03-13 22:28 UTC, danraponga commented on app/models/course.py
> +from sqlalchemy import select, func
useless imports

2024-03-15 01:28 UTC, danraponga approved these changes
Good job

2024-03-16 06:58 UTC, vladysllav requested changes

2024-03-16 06:58 UTC, vladysllav commented on app/crud/crud_course.py
> +    def get_ratings_for_course(self, db: Session, *, course_id: int):
Навіщо нам ця функція, якщо ми рейтинг в можелі отримуємо

2024-03-16 06:58 UTC, vladysllav commented on app/models/course.py
> +        return sum(rating.value for rating in self.course_ratings) / len(self.course_ratings)
Ти можеш використати метод mean з модулю statistics для цього

2024-03-16 17:44 UTC, merged