jwt auth flow has been rewritten.
vladysllav/LearnIT pull request #35
Opened 2024-03-04 23:22 UTC by danraponga

** A refresh token has been added, which can be used to refresh the access token.

** Methods for creating and decoding the refresh token have been created.

** Unique lifetimes have been created for each token type: the access token has a 30-minute lifetime, while the refresh token has a 7-day lifetime.

* Unique secret keys have been created for each token type.

* New schemas have been created.

*The sign-up flow has been changed: it now returns user details along with access and refresh tokens.

2024-03-06 04:05 UTC, vladysllav requested changes
Залишив невеличкий коммент, все інше гуд

2024-03-06 04:05 UTC, vladysllav commented on app/core/security.py
> +    secret_key = settings.JWT_REFRESH_SECRET_KEY
Можна одразу константи передавати в функцію, а не присваювати значення в змінні

2024-03-06 04:05 UTC, vladysllav commented on app/core/security.py
> +        algorithm = ALGORITHM
Так само, навіщо тут змінна

2024-03-06 04:05 UTC, vladysllav commented on app/core/security.py
> +    url = f'https://0.0.0.0:8000/api/users/activate/{token}'
Чому в нас домен тут прописаний, на різних енвах він же буде різний, це повинно бути у сетінгах(домен) а /api/users... вже додавати до нього

2024-03-06 15:47 UTC, danraponga commented on app/core/security.py
> +    secret_key = settings.JWT_REFRESH_SECRET_KEY
fixed

2024-03-06 15:47 UTC, danraponga commented on app/core/security.py
> +        algorithm = ALGORITHM
fixed

2024-03-06 15:47 UTC, danraponga commented on app/core/security.py
> +    url = f'https://0.0.0.0:8000/api/users/activate/{token}'
fixed

2024-03-08 03:27 UTC, vladysllav approved these changes

2024-03-08 18:16 UTC, merged