Lit 16.password validation
vladysllav/LearnIT pull request #36
Opened 2024-03-05 23:30 UTC by danraponga

Allow to register only if password has at least 1 number, 1 letter and 1 uppercase letter.

2024-03-06 04:09 UTC, vladysllav requested changes

2024-03-06 04:09 UTC, vladysllav commented on app/utils.py
> +def validate_password(password: str) -> tuple[bool, str]:
Цей метод краще до сервісу додати. Бо це відноситься виключно до юзера, а не глобально, в утілсах краще зберігати те що до всього проекту відноситься, а якщо воно чисто до юзера, то краще створити метод в юзерсервісі

2024-03-07 00:44 UTC, danraponga commented on app/utils.py
> +def validate_password(password: str) -> tuple[bool, str]:
FIXED

2024-03-08 03:26 UTC, vladysllav approved these changes

2024-03-08 18:32 UTC, merged