Opportunity to add users to Course was implemented. (GET, POST, PATCH…
vladysllav/LearnIT pull request #37
Opened 2024-03-21 17:21 UTC by Danemm99

…, DELETE methods).

2024-03-22 08:51 UTC, vladysllav requested changes

2024-03-22 08:51 UTC, vladysllav commented on app/api/courses/routes.py
> +@router.patch("/courses/{course_id}/users/{user_id}", dependencies=[Depends(allow_create_resource)])
Чому тут є courses на почтаку урла а в інших немає?

2024-03-22 08:51 UTC, vladysllav commented on app/crud/crud_course.py
> +    def add_user(self, db: Session, course: Course, user: User):
Краще назви add_user_to_course, щоб було зрозуміліше, а то можна подумати що метод просто створює користувача

2024-03-22 08:51 UTC, vladysllav commented on app/crud/crud_course.py
> +    def remove_user(self, db: Session, course: Course, user: User):
Так само і тут

2024-03-22 08:51 UTC, vladysllav commented on app/crud/crud_course.py
> +        return {"course_id": res_association[1], "user_id": res_association[0]}
Не найкращий варік за індексом звертатись, краще явно використовуй user_id та course_id

2024-03-22 15:38 UTC, Danemm99 commented on app/api/courses/routes.py
> +@router.patch("/courses/{course_id}/users/{user_id}", dependencies=[Depends(allow_create_resource)])
Fixed

2024-03-22 15:38 UTC, Danemm99 commented on app/crud/crud_course.py
> +    def add_user(self, db: Session, course: Course, user: User):
Fixed

2024-03-22 15:38 UTC, Danemm99 commented on app/crud/crud_course.py
> +    def remove_user(self, db: Session, course: Course, user: User):
Fixed

2024-03-22 15:38 UTC, Danemm99 commented on app/crud/crud_course.py
> +        return {"course_id": res_association[1], "user_id": res_association[0]}
Fixed

2024-03-25 11:19 UTC, vladysllav approved these changes

2024-03-25 17:42 UTC, merged