add sign up for new students
vladysllav/LearnIT pull request #5
Opened 2023-09-21 12:31 UTC by goldaev51

2023-09-21 12:53 UTC, vladysllav requested changes

2023-09-21 12:53 UTC, vladysllav commented on app/api/users/routes.py
> +@router.post("/sign_up", response_model=schemas.Token)
Роути краще робити через дефіс -> /sign-up/

2023-09-21 12:53 UTC, vladysllav commented on app/api/users/routes.py
> +    user_auth = crud.user.authenticate(
Навіщо ти додатково перевіряєш юзера, який тільки що був створений? В тебе ж вже є обʼєкт юзера, тільки но створенного

2023-09-21 12:53 UTC, vladysllav commented on app/crud/crud_user.py
> +        user_type = getattr(obj_in, 'type', UserType.student)
obj_in - має можливість отримати доступ до даних як у словнику, тому не потрібно окремо тип отримувати, можна це зробити вже у рядку де ти передаєш це значення

2023-09-21 12:53 UTC, vladysllav commented on app/crud/crud_user.py
>          db_obj = User(
Краще спочатку замінити два значення у обʼєкті obj_in, а потім просто зробити звичайне розпакування **, а не передавати коен атрибут окремо

2023-09-21 12:53 UTC, vladysllav commented on app/schemas/user.py
>      password: Optional[str] = Field(None, example="newsecurepassword")
Пароля на редагуванні не повинно бути, пароль можна змінити лише за допомогою change password функціоналу, окремо створенного для зміни паролю

2023-09-21 13:01 UTC, goldaev51 commented on app/api/users/routes.py
> +@router.post("/sign_up", response_model=schemas.Token)
Там просто всі інші роути /endpoint, тому зробив /sign_up

2023-09-21 13:03 UTC, goldaev51 commented on app/api/users/routes.py
> +    user_auth = crud.user.authenticate(
Не зрозумів, create - створює юзера, authenticate - логінить та повертає jwt token

2023-09-21 13:05 UTC, goldaev51 commented on app/crud/crud_user.py
> +        user_type = getattr(obj_in, 'type', UserType.student)
Схема UserCreate - має type, схема яку я передаю(UserSignUp) - не має type

2023-09-21 13:06 UTC, goldaev51 commented on app/schemas/user.py
>      password: Optional[str] = Field(None, example="newsecurepassword")
Зрозумів, тоді приберу усюди крім sign_up

2023-09-21 13:10 UTC, goldaev51 commented on app/crud/crud_user.py
> +        user_type = getattr(obj_in, 'type', UserType.student)
В нас просто є ще єндпоінт 
@router.post("/", response_model=schemas.User)
def create_user(
        *,
        db: Session = Depends(deps.get_db),
        user_in: schemas.UserCreate,
        current_user: models.User = Depends(deps.get_current_active_superuser),
) -> Any:

Це коли суперюзер самостійно створює нових користувачів, чи взагалі прибрати цей create_user?

2023-09-22 11:37 UTC, vladysllav approved these changes

2023-09-22 11:38 UTC, merged