Created a separate folder for dependencies(deps.py). Fixed imports in files that used dependencies: auth/routes and user/routes
vladysllav/LearnIT pull request #6
Opened 2023-10-03 15:54 UTC by danraponga

2023-10-03 19:00 UTC, vladysllav requested changes

2023-10-03 19:00 UTC, vladysllav commented on app/dependencies/deps.py
Тобі потрібно було створити окремі файли для user dependencies та для auth dependencies назви просто user та auth

2023-10-03 23:41 UTC, danraponga reviewed
трохи підправив імпорти, які не використовуються

2023-10-04 06:32 UTC, vladysllav commented on app/api/auth/routes.py
> +from app.dependencies import base
Краще явно імпортувати методи по типу from app.dependencies.base import get_db

2023-10-04 06:32 UTC, vladysllav commented on app/api/users/routes.py
> +from app.dependencies import base
Так само тут

2023-10-04 06:33 UTC, vladysllav requested changes
Виправ коментар і можеш одразу заливати

2023-10-06 10:51 UTC, vladysllav approved these changes

2023-10-06 12:13 UTC, danraponga commented on app/dependencies/deps.py
i divided the file differently: into basic (where we have get_db controller) and user logic. i did this because we don't have obvious auth logic.

2023-10-06 12:13 UTC, danraponga commented on app/api/auth/routes.py
> +from app.dependencies import base
fixed

2023-10-06 12:13 UTC, danraponga commented on app/api/users/routes.py
> +from app.dependencies import base
fixed

2023-10-06 12:14 UTC, merged