add models Course and UserCourse, updated User model for relations wi…
vladysllav/LearnIT pull request #7
Opened 2023-10-03 17:46 UTC by goldaev51

…th created models

2023-10-04 06:36 UTC, vladysllav commented on app/models/course.py
> +    rating = Column(Float, nullable=True)
Це поле зайве, ми цей функціонал поки не обговорювали, у схемі я поля сильно не дивився. А на майбутне ми будемо це поле разувати, бо рейтинг це буде окрема таблиця

2023-10-04 06:41 UTC, vladysllav requested changes

2023-10-04 06:41 UTC, vladysllav commented on app/models/user_cource.py
Для цієї таблиці не потрібно створювати окремий клас, ти можеш у файлі course написати цю таблицю

2023-10-04 06:41 UTC, vladysllav commented on app/models/course.py
> +    lecturer_id = Column(Integer, ForeignKey('user.id'), nullable=False)
Це поле нам не потрібно, бо не завжди в нас буде юзер зареєстрований лектор, уяви що ми просто додали якийсь курс, ми ж не будемо спеціально створювати для цього юзера, краще цю інфу ми статично будемо зберігати у майбутньому.

2023-10-04 06:41 UTC, vladysllav commented on app/models/user.py
> +    user_courses = relationship("UserCourse", back_populates="user")
Перейменуй у courses, а вище видали, бо лекторів не буде

2023-10-08 19:53 UTC, goldaev51 commented on app/models/course.py
> +    rating = Column(Float, nullable=True)
Прибрав rating

2023-10-08 19:53 UTC, goldaev51 commented on app/models/user_cource.py
Переніс user_course у course файл

2023-10-08 19:55 UTC, goldaev51 commented on app/models/course.py
> +    lecturer_id = Column(Integer, ForeignKey('user.id'), nullable=False)
Я мав на увазі, щоб у таблиці це поле помітити як lecturer_id  - який по факту буде просто юзером. Це поле потрібне, бо воно є FK на таблицю юзера, що у курса є юзер, який його створив

2023-10-08 20:03 UTC, goldaev51 commented on app/models/user.py
> +    user_courses = relationship("UserCourse", back_populates="user")
Вище описав, що я маю на увазі стосовно лекторів. У полі user_courses - перейменував у courses

2023-10-09 08:54 UTC, vladysllav commented on app/models/course.py
> +    lecturer_id = Column(Integer, ForeignKey('user.id'), nullable=False)
Тоді це не lecturer це created_by поле краще назвати, типу хто створив курс, а не хто його викладач, бо курс можу створити я, а викладач буде хтось інший, тому перейменуй, щоб не було недорозумінь

2023-10-09 09:12 UTC, merged