removed all related item code and created new migration that deletes item table
vladysllav/LearnIT pull request #9
Opened 2023-10-04 00:25 UTC by danraponga

deleted items models, schemas, crud. removed items code from db/base, models init, schemas init. created migration that deletes item.

2023-10-04 06:43 UTC, vladysllav requested changes
Потрібно розібратись з тим як міграції працюють

2023-10-04 06:43 UTC, vladysllav commented on alembic/versions/2023_08_21_0936-c62a40b37efb_initial_migration.py
Міграціі чіпати НІ В КОЄМУ РАЗІ не можна

2023-10-04 06:43 UTC, vladysllav commented on app/db/base.py
> +from app.db.base_class import Base  # noqa  # noqa
Навіщо тут два комента? Одного вистачить

2023-10-04 06:43 UTC, vladysllav commented on app/models/item.py
При зміні моделей тобі необхідно сгенерувати нову алембік міграцію

2023-10-06 10:52 UTC, vladysllav approved these changes

2023-10-06 12:06 UTC, danraponga commented on alembic/versions/2023_08_21_0936-c62a40b37efb_initial_migration.py
fixed

2023-10-06 12:06 UTC, danraponga commented on app/db/base.py
> +from app.db.base_class import Base  # noqa  # noqa
fixed

2023-10-06 12:06 UTC, danraponga commented on app/models/item.py
fixed

2023-10-06 12:07 UTC, merged